{"name": "test_login[admin@email.com-admin@1234545]", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Service /usr/bin/safaridriver unexpectedly exited. Status code was: 1", "trace": "request = <SubRequest 'setup' for <Function test_login[admin@email.com-admin@1234545]>>\n\n    @pytest.fixture(scope=\"class\")\n    def setup(request):  # you use 'request' when you want to use the driver from 'fixture' into any test class\n        # 'request' is a pre-defined fixture /request is a module\n        # so now where ever you use the 'setup' method you can access the driver now\n        # fixture 'request' by default set to 'None'\n        wdf = WebDriverFactory(\"chrome\")  # created an object from 'WebDriverFactory' class\n    \n>       driver = wdf.getWebDriverInstance()  # this method imported from 'WebDriverFactory' class\n\ntests/conftest.py:15: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nbase/webdriverfactory.py:22: in getWebDriverInstance\n    driver=webdriver.Safari()\nvenv/lib/python3.11/site-packages/selenium/webdriver/safari/webdriver.py:51: in __init__\n    self.service.start()\nvenv/lib/python3.11/site-packages/selenium/webdriver/common/service.py:108: in start\n    self.assert_process_still_running()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.safari.service.Service object at 0x111004590>\n\n    def assert_process_still_running(self) -> None:\n        \"\"\"Check if the underlying process is still running.\"\"\"\n        return_code = self.process.poll()\n        if return_code:\n>           raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")\nE           selenium.common.exceptions.WebDriverException: Message: Service /usr/bin/safaridriver unexpectedly exited. Status code was: 1\n\nvenv/lib/python3.11/site-packages/selenium/webdriver/common/service.py:121: WebDriverException"}, "parameters": [{"name": "email", "value": "'admin@email.com'"}, {"name": "password", "value": "'admin@1234545'"}], "start": 1737408395762, "stop": 1737408395762, "uuid": "8f0d2dc8-1d3b-4bc6-a143-ad239217c55d", "historyId": "edddadecaa2f284a8d2475d68504c2d8", "testCaseId": "3363a3c2a0dcd6814d51cf393a310bbb", "fullName": "tests.test_login_script.TestLoginScenario#test_login", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_script"}, {"name": "subSuite", "value": "TestLoginScenario"}, {"name": "host", "value": "Kriss-MacBook-Pro.local"}, {"name": "thread", "value": "3642-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_script"}]}